[package]
name = "src"
version = "0.1.0"
edition = "2024"

[dependencies]
tokenizer = { path = "./tokenizer" }
parser = { path = "./parser" }

[workspace]
members = [
    "tokenizer_macro",
    "tokenizer_trait",
    "ast_trait",
    "ast_macros",
    "parser",
]
